sources:
  docker:
    type: docker_logs
    docker_host: "unix:///var/run/docker.sock"

sinks:
  loki:
    type: loki
    inputs:
      - docker
    endpoint: http://loki:3100
    encoding:
      codec: json
    labels:
      instance: "{{ label.com.docker.swarm.task.id }}"
      node: "{{ label.com.docker.swarm.node.id }}"
      job: "{{ label.com.docker.swarm.service.name }}"
